version: "3.8"

services:
    db:
      image: mongo:latest
      container_name: fete-db
      hostname: fetedb
      environment:
       - PUID=111
       - PGID=111
      volumes:
       - fete_data:/data/db
      ports:
       - 27017:27017
      restart: unless-stopped
      networks:
       - api-net

    api:
      image: feteapi:latest
      container_name: fete
      hostname: fete
      ports:
        - 8080:8080
        - 8081:8081
      depends_on:
       - fetedb
      networks:
        - api-net

networks:
  api-net:
    name: api-net
